### PR TITLE
Added Polyak update rate for soft DQN target network updates

### PR DESCRIPTION
**Pull request by manjavacas**
## Description

According to #346, the **Polyak update rate** (`tau`) has been included as an argument to `dqn.py` and `dqn_atari.py` implementations.

It will allow soft updates of the target network, as already done for `dqn_jax.py`.

## Types of changes

- [ ] Bug fix
- [x] New feature
- [ ] New algorithm
- [x] Documentation

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/vwxyzjn/cleanrl/blob/master/CONTRIBUTING.md) guide (**required**).
- [x] I have ensured `pre-commit run --all-files` passes (**required**).
- [x] I have updated the documentation and previewed the changes via `mkdocs serve`.
- [ ] I have updated the tests accordingly (if applicable).

If you are adding new algorithm variants or your change could result in performance difference, you may need to (re-)run tracked experiments. See https://github.com/vwxyzjn/cleanrl/pull/137 as an example PR. 
- [ ] I have contacted [vwxyzjn](https://github.com/vwxyzjn) to obtain access to the [openrlbenchmark W&B team](https://wandb.ai/openrlbenchmark) (**required**).
- [ ] I have tracked applicable experiments in [openrlbenchmark/cleanrl](https://wandb.ai/openrlbenchmark/cleanrl) with `--capture-video` flag toggled on (**required**).
- [ ] I have added additional documentation and previewed the changes via `mkdocs serve`.
    - [ ] I have explained note-worthy implementation details.
    - [ ] I have explained the logged metrics.
    - [ ] I have added links to the original paper and related papers (if applicable).
    - [ ] I have added links to the PR related to the algorithm variant.
    - [ ] I have created a table comparing my results against those from reputable sources (i.e., the original paper or other reference implementation).
    - [ ] I have added the learning curves (in PNG format).
    - [ ] I have added links to the tracked experiments.
    - [ ] I have updated the overview sections at the [docs](https://docs.cleanrl.dev/rl-algorithms/overview/) and the [repo](https://github.com/vwxyzjn/cleanrl#overview)
- [ ] I have updated the tests accordingly (if applicable).

### CODE REVIEW

**Review by vwxyzjn — CHANGES_REQUESTED** [review]
Thanks for this PR. Could you add a note in implementation details section in the documentation /docs/rl-algorithms/dqn.md about that we implement target network update as a polyak update?

**Comment by manjavacas** [comment]
Sure! I have updated the documentation. Please let me know if you need anything else 😃

**Review by vwxyzjn — COMMENTED** [review]
Thanks for adding the docs. I just realized this — would you mind adding the same `--tau` argument to `dqn_jax.py` and `dqn_atari_jax.py`? I think you just need to replace 

https://github.com/vwxyzjn/cleanrl/blob/30381eea1aa37cbab0a7a16c47ce5ef0b39bf213/cleanrl/dqn_jax.py#L237

```
 q_state = q_state.replace(target_params=optax.incremental_update(q_state.params, q_state.target_params, args.tau)) 
```

Similarly, please update docs to reflect this change.

**Review by vwxyzjn — APPROVED** [review]

**Comment by vwxyzjn** [comment]
Thanks for the contribution! @manjavacas

**Comment by vwxyzjn** [comment]
This PR closes https://github.com/vwxyzjn/cleanrl/issues/346.

**Comment by manjavacas** [comment]
> Thanks for the contribution! @manjavacas

Thanks to you for this great project! 
Looking forward to continue contributing :-)

**Pull request merged**
