### PR TITLE
Add gymnasium support to SAC

### PR DESCRIPTION
**Pull request by pseudo-rnd-thoughts**
## Types of changes

- [ ] Bug fix
- [x] New feature
- [ ] New algorithm
- [ ] Documentation

## Checklist:

- [x] I've read the [CONTRIBUTION](https://docs.cleanrl.dev/contribution/) guide (**required**).
- [x] I have ensured `pre-commit run --all-files` passes (**required**).
- [x] I have updated the tests accordingly (if applicable).
- [ ] I have updated the documentation and previewed the changes via `mkdocs serve`.
    - [ ] I have explained note-worthy implementation details.
    - [ ] I have explained the logged metrics.
    - [ ] I have added links to the original paper and related papers.

If you need to run benchmark experiments for a performance-impacting changes:

- [ ] I have contacted @vwxyzjn to obtain access to the [openrlbenchmark W&B team](https://wandb.ai/openrlbenchmark).
- [ ] I have used the [benchmark utility](/get-started/benchmark-utility/) to submit the tracked experiments to the [openrlbenchmark/cleanrl](https://wandb.ai/openrlbenchmark/cleanrl) W&B project, optionally with `--capture-video`.
- [ ] I have performed RLops with `python -m openrlbenchmark.rlops`.
    - For new feature or bug fix:
        - [ ] I have used the RLops utility to understand the performance impact of the changes and confirmed there is no regression.
    - For new algorithm:
        - [ ] I have created a table comparing my results against those from reputable sources (i.e., the original paper or other reference implementation).
    - [ ] I have added the learning curves generated by the `python -m openrlbenchmark.rlops` utility to the documentation.
    - [ ] I have added links to the tracked experiments in W&B, generated by `python -m openrlbenchmark.rlops ....your_args... --report`,  to the documentation.

### CODE REVIEW

**Comment by timoklein** [comment]
Hey there,
did you also run into [this issue](https://github.com/vwxyzjn/cleanrl/issues/379) while testing `sac_continuous_action.py`?

**Comment by qiuruiyu** [comment]
Hello! 
Are you still working on transmitting SAC from gym to gymnasium? And any problem did you met?

**Comment by pseudo-rnd-thoughts** [comment]
Hey, I think the only thing that I never completed was finishing the training, I had another project that required the compute time more so had to cancel it and never got back to this sadly. Otherwise, I believe, the code is updated but I might be wrong

**Comment by sdpkjc** [comment]
Because the MacOS MuJoCo test does not have Mesa installed, I have commented out that part of the test for now.

**Comment by sdpkjc** [comment]
After this PR is merged, all of our algorithms for the MuJoCo environments will have been migrated. Therefore, I've organized the test files and CI files in this PR.

**Comment by vwxyzjn** [comment]
> After this PR is merged, all of our algorithms for the MuJoCo environments will have been migrated. Therefore, I've organized the test files and CI files in this PR.

Sounds great! Thanks @sdpkjc

**Comment by sdpkjc** [comment]
pr-378
pr-378-time

**Review by vwxyzjn — APPROVED** [review]
Fantastic! Feel free to merge!

**Comment by sdpkjc** [comment]
pr-378-atari
pr-378-time

Since `sac_atari` did not have the experiment with `rlops-pilot` tag for comparison, I used the previous experiment with `pr-270` tag as a comparison.

**Pull request merged**
