### PR TITLE
TD3: fixed dimension of clipped_noise for target actions, added noise …

### LINKED ISSUE #279: TD3 policy noise bugs
## Problem Description

There are two bugs in 
https://github.com/vwxyzjn/cleanrl/blob/e466f6efb251462de2b80f064133f32cb5d83e22/cleanrl/td3_continuous_action.py#L209
(1) The same noise is used for all the batch actions.
(2) Action scale is not taken into account for the noise. 

## Checklist
- [x] I have installed dependencies via `poetry install` (see [CleanRL's installation guideline](https://docs.cleanrl.dev/get-started/installation/).
- [x] I have checked that there is no similar [issue](https://github.com/vwxyzjn/cleanrl/issues) in the repo (required)

## Current Behavior
(1) Takes noise size from actions[0]
(2) No scaling is performed on the noise, but the policy could have a different scale (see
https://github.com/vwxyzjn/cleanrl/blob/e466f6efb251462de2b80f064133f32cb5d83e22/cleanrl/td3_continuous_action.py#L114
)

## Expected Behavior
(1) Should take shape of data.actions
(2) Scale the noise according to the policy scale

## Possible Solution
(1) replace torch.Tensor(actions[0]) with torch.Tensor(data.actions)
(2) Multiply the noise with target_actor.action_scale

## Steps to Reproduce

1. Run the script https://github.com/vwxyzjn/cleanrl/blob/master/cleanrl/td3_continuous_action.py, stop on line 209 to view shapes.

### PR DESCRIPTION
**Pull request by dosssman**
## Description
Closes #279.

- td3_continuous_action.py: noise sampled to compute the Q network update target matches action dimensions in the buffer
- td3_continuous_action.py: aforementioned noise is also scaled to match the scaling range of the actions.

## Types of changes

- [x] Bug fix
- [ ] New feature
- [ ] New algorithm
- [ ] Documentation

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/vwxyzjn/cleanrl/blob/master/CONTRIBUTING.md) guide (**required**).
- [x] I have ensured `pre-commit run --all-files` passes (**required**).
- ~~[ ] I have updated the documentation and previewed the changes via `mkdocs serve`.~~
- [x] I have updated the tests accordingly (if applicable).

If you are adding new algorithms or your change could result in performance difference, you may need to (re-)run tracked experiments. See https://github.com/vwxyzjn/cleanrl/pull/137 as an example PR. 
- [x] I have contacted [vwxyzjn](https://github.com/vwxyzjn) to obtain access to the [openrlbenchmark W&B team](https://wandb.ai/openrlbenchmark) (**required**).
- [x] I have tracked applicable experiments in [openrlbenchmark/cleanrl](https://wandb.ai/openrlbenchmark/cleanrl) with `--capture-video` flag toggled on (**required**).
- [x] I have added additional documentation and previewed the changes via `mkdocs serve`.
    - [x] I have explained note-worthy implementation details.
    - [x] I have explained the logged metrics.
    - [x] I have added links to the original paper and related papers (if applicable).
    - [x] I have added links to the PR related to the algorithm.
    - [x] I have created a table comparing my results against those from reputable sources (i.e., the original paper or other reference implementation).
    - [x] I have added the learning curves (in PNG format with `width=500` and `height=300`).
    - [x] I have added links to the tracked experiments.
    - [x] I have updated the overview sections at the [docs](https://docs.cleanrl.dev/rl-algorithms/overview/) and the [repo](https://github.com/vwxyzjn/cleanrl#overview)
- [x] I have updated the tests accordingly (if applicable).

### CODE REVIEW

**Comment by dosssman** [comment]
@vwxyzjn td3 continuous JAX variant will probably be affected too though.

**Comment by vwxyzjn** [comment]
@joaogui1 could you check if TD3 (JAX) will be affected?

**Comment by joaogui1** [comment]
@vwxyzjn check whether the jax implementation affected by this PR or if it will also need a fix like this PR?

**Comment by vwxyzjn** [comment]
@joaogui1, the latter :)

**Comment by joaogui1** [comment]
Got it, it will need to be fix, creating the PR this moment

**Comment by vwxyzjn** [comment]
@dosssman thank you for the PR! Would you mind running some benchmark experiments to see if this change has a significant impact on the performance? If not, we don't even have to update the docs.

https://github.com/vwxyzjn/cleanrl/blob/f0bbf49ff2f0786882dc8ac0eded8b483a36b6ca/benchmark/td3.sh#L3-L7

**Comment by dosssman** [comment]
There is a performance regression on the Walker2d env, but the others are only marginally affected:

Report [here](https://wandb.ai/openrlbenchmark/openrlbenchmark/reports/CleanRL-s-TD3-TD3-Trgt-Action-Noise-Sample-Check--VmlldzoyNzQ3NjE5)

**Comment by vwxyzjn** [comment]
Hmm the experiments failed... Would you mind re-running it?
image

**Comment by vwxyzjn** [comment]
Given that this is a performance-impacting change, I am re-running the benchmark now.

**Comment by vwxyzjn** [comment]
No material change to the performance. I am going to update the docs. The regression report is at https://wandb.ai/openrlbenchmark/cleanrl-cache/reports/-281-CleanRL-s-TD3-TD3-Trgt-Action-Noise-Sample-Check--VmlldzoyODE5MTg0

image
image
image
image
image
image

**Review by vwxyzjn — APPROVED** [review]

**Pull request merged**
