### PR TITLE
Sebula PPO (EnvPool's async API)

### PR DESCRIPTION
**Pull request by vwxyzjn**
## Description

Todo items:
- [x] SPMD learner ✅ helps!
- [x] `SPS_update` calculation for the actor ✅ helps!
- [x] multiple threads per actor? ✅ helps!
- [x] remove b_inds 🤔 same speed!
- [x] `jnp.array_split` within JIT 🤔 same speed!
- [ ] integer division issue -- `async_update` is off (https://wandb.ai/costa-huang/cleanRL/reports/4-vs-3-learner-devices--VmlldzozNDg4MDE5)
- [ ] possibility of hanging: https://wandb.ai/openrlbenchmark/cleanrl/runs/3too0kec?workspace=user-costa-huang
- [ ] can you still replicate sample efficiency result with 1GPU?

More experiments
- [ ] use EnvPool's XLA interface (it's going to be faster, but likely not worth it because it limits the application to non-C++ envs)
- [ ] use larger batch size...?
- [ ] allow using multiple actor GPUs
- [ ] larger models? (e.g., muesli paper's model size)
- [ ] potentially a data worker? (e.g., [dm-haiku's impala](https://github.com/deepmind/dm-haiku/blob/970d3df2f55dc087ee9e373a841d09b9adef3346/examples/impala/learner.py#L169-L188))
- [ ] study the balance between actor and learner?
- [ ] automatically calculate the queue size
- [ ] implement something like https://github.com/alex-petrenko/faster-fifo that uses one lock to get many items.

hypothesis:
* suppose we have an `update` function that runs on GPU1, then the execution of `update` will block the `jax.device_put_sharded` call in a separate thread that tries to put data from GPU0 to GPU1. Not sure if this is the case for TPU as well. 
    * ✅ related to this issue: having a dedicated GPU actor helps compared to actor using GPU 0 and learners using GPU 0 1 2 3

## Types of changes

- [ ] Bug fix
- [ ] New feature
- [ ] New algorithm
- [ ] Documentation

## Checklist:

- [ ] I've read the [CONTRIBUTION](https://github.com/vwxyzjn/cleanrl/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] I have ensured `pre-commit run --all-files` passes (**required**).
- [ ] I have updated the documentation and previewed the changes via `mkdocs serve`.
- [ ] I have updated the tests accordingly (if applicable).

If you are adding new algorithm variants or your change could result in performance difference, you may need to (re-)run tracked experiments. See https://github.com/vwxyzjn/cleanrl/pull/137 as an example PR. 
- [ ] I have contacted [vwxyzjn](https://github.com/vwxyzjn) to obtain access to the [openrlbenchmark W&B team](https://wandb.ai/openrlbenchmark) (**required**).
- [ ] I have tracked applicable experiments in [openrlbenchmark/cleanrl](https://wandb.ai/openrlbenchmark/cleanrl) with `--capture-video` flag toggled on (**required**).
- [ ] I have added additional documentation and previewed the changes via `mkdocs serve`.
    - [ ] I have explained note-worthy implementation details.
    - [ ] I have explained the logged metrics.
    - [ ] I have added links to the original paper and related papers (if applicable).
    - [ ] I have added links to the PR related to the algorithm variant.
    - [ ] I have created a table comparing my results against those from reputable sources (i.e., the original paper or other reference implementation).
    - [ ] I have added the learning curves (in PNG format).
    - [ ] I have added links to the tracked experiments.
    - [ ] I have updated the overview sections at the [docs](https://docs.cleanrl.dev/rl-algorithms/overview/) and the [repo](https://github.com/vwxyzjn/cleanrl#overview)
- [ ] I have updated the tests accordingly (if applicable).

### CODE REVIEW

**Comment by vwxyzjn** [comment]
Hey @51616 happy new year. This is the implementation that works with EnvPool’s async API, which requires quite a bit a refactoring. It should scale to cases where the environments are slow or/and the models are large. I’m running some benchmark experiments, but figured you might be interested in taking a look :)

**Comment by 51616** [comment]
@vwxyzjn Any specific part you want me to take a look at? Btw, I'm not quite familiar with async environments but I can help you review/test the code if needed.

**Comment by vwxyzjn** [comment]
Seems to work ok now... This opens up new possibilities because we can use SPMD for learner updates. 

image

**Comment by shermansiu** [comment]
Thanks, good to know!

**Comment by vwxyzjn** [comment]
## `threading` is fine (`multiprocessing` not necessary)

`sebulba_ppo_envpool_new.py` in [ab732a6](https://github.com/vwxyzjn/cleanrl/pull/338/commits/ab732a6386b3f7e75302d5144cdbc375f834aa21) basically running the learners non-stop while trying to step the actors as fast as possible. There's no communication between the actor and learners, so I was just testing to see if the learners would slow down the actor. 

There were two settings:
- [ ] `--actor-device-ids 0 --learner-device-ids 1 2` actor and learners have separate devices
- [ ] `--actor-device-ids 0 --learner-device-ids 0 1` actor shares one of the learners' devices.

The following figures suggests `--actor-device-ids 0 --learner-device-ids 1 2` has much higher SPS, meaning having separate devices is key to not slowing down the actor, especially when the learning time is long. (e.g., when learning time is short, `--actor-device-ids 0 --learner-device-ids 0 1` might perform just as fast)

image

I think under the hood this means calling `multi_device_update` will utilize the learners' devices and block access to those devices from other python threads, effectively slowing down the actor. However, if the actor has its own device, then the actor's speed is unaffected.

**Comment by vwxyzjn** [comment]
Supported multiple threads on an actor according to the podracer paper
> To generate experience, we use (at least) one separate Python thread for each actor core [...] To
make efficient use of the actor cores, it is essential that while a Python thread is stepping a batch of
environments, the corresponding TPU core is not idle. This is achieved by creating multiple Python
threads per actor core, each with its own batched environment. They threads alternate in using the
same actor core, without manual synchronization

image

**Comment by vwxyzjn** [comment]
[a93a1f5](https://github.com/vwxyzjn/cleanrl/pull/338/commits/a93a1f5381a9ab5d1f403e871b6ee14f9751576e)  calls `jax.device_put_sharded` in the learner, which makes the actor thread runs a lot faster. The learning time also suffers very little time, which is great. My hypothesis is that:
* suppose we have an `update` function that runs on GPU1, then the execution of `update` will block the `jax.device_put_sharded` call in a separate thread that tries to put data from GPU0 to GPU1. Not sure if this is the case for TPU as well.
* [a93a1f5](https://github.com/vwxyzjn/cleanrl/pull/338/commits/a93a1f5381a9ab5d1f403e871b6ee14f9751576e) removes the call of `device_put_sharded` from the actor threads, therefore unblocking the actor.
> **Note** This is a major difference from the podracer paper, in which I presume the `jax.device_put_sharded` happens in the actor threads

image

**Comment by vwxyzjn** [comment]
[0eefb50](https://github.com/vwxyzjn/cleanrl/pull/338/commits/0eefb508b80954ff3809165d487ec996513daed2) uses `jax.put_device_replicated` for the `agent_state` which slightly improves SPS. 

image

**Comment by vwxyzjn** [comment]
[0dd591c](https://github.com/vwxyzjn/cleanrl/pull/338/commits/0dd591c2c628624da1f8aa042366311ec1d7735d) blocks the actor for 10 seconds during the first, second, and the third rollout. Experiments found that it could improve SPS a bit and actually improves performance as well — without this commit, the actor is always generating experiences for outdated parameters (1 update behind; see `stats/param_queue_size`) 

image

**Comment by vwxyzjn** [comment]
Known issues:
- [ ] possibility of hanging: https://wandb.ai/openrlbenchmark/cleanrl/runs/3too0kec?workspace=user-costa-huang

**Comment by vwxyzjn** [comment]
Was able to match DM's sebubla's (https://arxiv.org/pdf/2104.06272.pdf) architecture performance to some capacity. My prototype (CleanBa PPO — stands for cleanrl's sebubla PPO) can outperform the original IMPALA (deep net setting, Espeholt et al., 2018), with 5 A100 GPUs (1 actor GPU, 4 learner GPU) and 16 CPU cores for envpool. Still WIP; need to fix some bugs.

Current results: 

image
cleanrl_sebulba_ppo_vs_baselines-time

**Comment by vwxyzjn** [comment]
Got an error

```
                                                               2023-02-17 06:08:24.084633: E external/org_tensorflow/tensorflow/tsl/distributed_runtime/coordination/coordination_service_agent.cc:481] Failed to disconnect from coordination service with status: DEADLINE_EXCEEDED: Deadline Exceeded
Additional GRPC error information from remote target unknown_target_for_coordination_leader:
:{"created":"@1676614104.084285325","description":"Error received from peer ipv4:26.0.134.228:64719","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Deadline Exceeded","grpc_status":4}. Proceeding with agent shutdown anyway.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/admin/home-costa/.cache/pypoetry/virtualenvs/cleanrl-BE0ShDkT-py3.8/lib/python3.8/site-packages/jax/_src/distributed.py", line 168, in shutdown
    global_state.shutdown()
  File "/admin/home-costa/.cache/pypoetry/virtualenvs/cleanrl-BE0ShDkT-py3.8/lib/python3.8/site-packages/jax/_src/distributed.py", line 87, in shutdown
    self.client.shutdown()
jaxlib.xla_extension.XlaRuntimeError: DEADLINE_EXCEEDED: Deadline Exceeded
Additional GRPC error information from remote target unknown_target_for_coordination_leader:
:{"created":"@1676614104.084285325","description":"Error received from peer ipv4:26.0.134.228:64719","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Deadline Exceeded","grpc_status":4}
    2023-02-17 06:08:24.405270: E external/org_tensorflow/tensorflow/tsl/distributed_runtime/coordination/coordination_service.cc:1129] Shutdown barrier in coordination service has failed: DEADLINE_EXCEEDED: Barrier timed out. Barrier_id: Shutdown::15630121101087999007 [type.googleapis.com/tensorflow.CoordinationServiceError='']. This suggests that at least one worker did not complete its job, or was too slow/hanging in its execution.
2023-02-17 06:08:24.405311: E external/org_tensorflow/tensorflow/tsl/distributed_runtime/coordination/coordination_service.cc:731] INTERNAL: Shutdown barrier has been passed with status: 'DEADLINE_EXCEEDED: Barrier timed out. Barrier_id: Shutdown::15630121101087999007 [type.googleapis.com/tensorflow.CoordinationServiceError='']', but this task is not at the barrier yet. [type.googleapis.com/tensorflow.CoordinationServiceError='']
2023-02-17 06:08:24.405379: E external/org_tensorflow/tensorflow/tsl/distributed_runtime/coordination/coordination_service.cc:449] Stopping coordination service as shutdown barrier timed out and there is no service-to-client connection.
2023-02-17 06:08:53.225236: E external/org_tensorflow/tensorflow/tsl/distributed_runtime/coordination/coordination_service_agent.cc:711] Coordination agent is in ERROR: INVALID_ARGUMENT: Unexpected task request with task_name=/job:jax_worker/replica:0/task:0
Additional GRPC error information from remote target unknown_target_for_coordination_leader:
:{"created":"@1676614133.225164768","description":"Error received from peer ipv4:26.0.134.228:64719","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Unexpected task request with task_name=/job:jax_worker/replica:0/task:0","grpc_status":3} [type.googleapis.com/tensorflow.CoordinationServiceError='']
2023-02-17 06:08:53.225277: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/distributed/client.cc:452] Coordination service agent in error status: INVALID_ARGUMENT: Unexpected task request with task_name=/job:jax_worker/replica:0/task:0
Additional GRPC error information from remote target unknown_target_for_coordination_leader:
:{"created":"@1676614133.225164768","description":"Error received from peer ipv4:26.0.134.228:64719","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Unexpected task request with task_name=/job:jax_worker/replica:0/task:0","grpc_status":3} [type.googleapis.com/tensorflow.CoordinationServiceError='']
2023-02-17 06:08:53.226009: F external/org_tensorflow/tensorflow/compiler/xla/pjrt/distributed/client.h:75] Terminating process because the coordinator detected missing heartbeats. This most likely indicates that another task died; see the other task logs for more details. Status: INVALID_ARGUMENT: Unexpected task request with task_name=/job:jax_worker/replica:0/task:0
Additional GRPC error information from remote target unknown_target_for_coordination_leader:
:{"created":"@1676614133.225164768","description":"Error received from peer ipv4:26.0.134.228:64719","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Unexpected task request with task_name=/job:jax_worker/replica:0/task:0","grpc_status":3} [type.googleapis.com/tensorflow.CoordinationServiceError='']
srun: error: ip-26-0-134-228: task 0: Aborted

```

**Comment by vwxyzjn** [comment]
Closed in favor of https://github.com/vwxyzjn/cleanba

**Pull request closed without merging**
