### PR TITLE
Isaac Gym Envs PPO updates

### PR DESCRIPTION
**Pull request by vwxyzjn**
## Description

Follow up on #232. 

## Types of changes

- [ ] Bug fix
- [x] New feature
- [ ] New algorithm
- [ ] Documentation

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/vwxyzjn/cleanrl/blob/master/CONTRIBUTING.md) guide (**required**).
- [x] I have ensured `pre-commit run --all-files` passes (**required**).
- [x] I have updated the documentation and previewed the changes via `mkdocs serve`.
- [ ] I have updated the tests accordingly (if applicable).

If you are adding new algorithms or your change could result in performance difference, you may need to (re-)run tracked experiments. See https://github.com/vwxyzjn/cleanrl/pull/137 as an example PR. 
- [x] I have contacted [vwxyzjn](https://github.com/vwxyzjn) to obtain access to the [openrlbenchmark W&B team](https://wandb.ai/openrlbenchmark) (**required**).
- [x] I have tracked applicable experiments in [openrlbenchmark/cleanrl](https://wandb.ai/openrlbenchmark/cleanrl) with `--capture-video` flag toggled on (**required**).
- [x] I have added additional documentation and previewed the changes via `mkdocs serve`.
    - [x] I have explained note-worthy implementation details.
    - [x] I have explained the logged metrics.
    - [x] I have added links to the original paper and related papers (if applicable).
    - [x] I have added links to the PR related to the algorithm.
    - [x] I have created a table comparing my results against those from reputable sources (i.e., the original paper or other reference implementation).
    - [x] I have added the learning curves (in PNG format with `width=500` and `height=300`).
    - [x] I have added links to the tracked experiments.
- [ ] I have updated the tests accordingly (if applicable).

### CODE REVIEW

**Comment by vwxyzjn** [comment]
Hey @dosssman and @Howuhh, would you mind trying this installation method? Installation Isaac Gym is not an easy step, and I want to make sure someone has tested the installation instruction. Thanks so much!

**Comment by yooceii** [comment]
Nice addition. One q: is it possible not to have a separate folder?

**Review by yooceii — APPROVED** [review]

**Comment by vwxyzjn** [comment]
> Nice addition. One q: is it possible not to have a separate folder?

Thanks @yooceii for the review. It's not really possible if we want to lock dependencies for `isaacgym`. `isaacgym` is not a PyPi package (see https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/issues/23), so creating a separate folder w/ our pre-locked poetry files was necessary.

**Comment by vwxyzjn** [comment]
Thanks @markelsanz14. Merging now.

**Pull request merged**
