### PR TITLE
added gamma to reward normalization wrappers

### PR DESCRIPTION
**Pull request by Howuhh**
## Description
Fixes incorrect gamma in reward normalization wrapper for non-default gamma's. See https://github.com/vwxyzjn/cleanrl/issues/203.

## Types of changes

- [x] Bug fix
- [ ] New feature
- [ ] New algorithm
- [ ] Documentation

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/vwxyzjn/cleanrl/blob/master/CONTRIBUTING.md) guide (**required**).
- [x] I have ensured `pre-commit run --all-files` passes (**required**).

If you are adding new algorithms or your change could result in performance difference, you may need to (re-)run tracked experiments. See https://github.com/vwxyzjn/cleanrl/pull/137 as an example PR. 
- [x] I have contacted @vwxyzjn to obtain access to the [openrlbenchmark W&B team](https://wandb.ai/openrlbenchmark) (**required**).
- [x] I have tracked applicable experiments in [openrlbenchmark/cleanrl](https://wandb.ai/openrlbenchmark/cleanrl) with `--capture-video` flag toggled on (**required**).
- [x] I have added additional documentation and previewed the changes via `mkdocs serve`.
    - [x] I have explained note-worthy implementation details.
    - [x] I have added the learning curves (in PNG format with `width=500` and `height=300`).
    - [x] I have added links to the tracked experiments.

### CODE REVIEW

**Comment by Howuhh** [comment]
@vwxyzjn To be honest, I think this is a bug in original code, not a feature, so it will be more correct to rerun for correct results. However, procgen is image based env and for now I don't have resources to train on images.

**Comment by vwxyzjn** [comment]
Running the PPO experiments now

image


Also tried a fun thing by adding a wandb tag like

```
WANDB_TAGS=$(git describe --tags)  xvfb-run -a python -m cleanrl_utils.benchmark \
    --env-ids starpilot bossfight bigfish \
    --command "poetry run python cleanrl/ppo_procgen.py --track --capture-video" \
    --num-seeds 3 \
    --workers 1
```

which produces runs like 

image


@dosssman I think this tagging system could somehow help us phase out past openrlbenchmark experiments without deleting them. I will have to think about the workflow a bit more.

**Comment by vwxyzjn** [comment]
Following up here

image
image
image

**Comment by vwxyzjn** [comment]
The bigfish performance degradation could easily be due to a random seed.

**Comment by vwxyzjn** [comment]
image
image
image

No major performance regression. Going to document this change and merge.

**Comment by vwxyzjn** [comment]
I have just updated all of the experiments and documentation. @Howuhh @dosssman could you give it a pass, please? Thank you!

**Comment by Howuhh** [comment]
@vwxyzjn Seems okay to me. Thanks for redoing the experiments btw.

**Pull request merged**
